---

- name: Include common tasks
  include_tasks: common.yml
  tags:
    - deploy
     
- name: Include type specific tasks
  include_tasks: "{{ lookup('vars',app_name)['type'] }}.yml"
  tags:
    - deploy
     
- name: Include tasks for remove
  include_tasks: remove.yml
  tags:
    - remove

- name: Force to check service
  command: /bin/true
  notify:
    - Check service
  tags:
    - deploy


